# Generated by Django 5.2.4 on 2026-03-28 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default="🏆 Nagpur's #1 Pickle Store", max_length=200)),
                ('title_line1', models.CharField(default='Discover', max_length=200)),
                ('title_highlight', models.CharField(default='Rare & Exclusive', max_length=200)),
                ('title_line2', models.CharField(default='Pickle Brands', max_length=200)),
                ('subtitle', models.TextField(default='Handpicked regional pickles from Andhra, Rajasthan, Punjab & more — not available in local stores. Order online with 24-hour delivery across Nagpur.')),
                ('btn_primary_text', models.CharField(default='🛍️ Shop Now', max_length=100)),
                ('btn_primary_url', models.CharField(default='/products/', max_length=300)),
                ('btn_secondary_text', models.CharField(default='💬 Order on WhatsApp', max_length=100)),
                ('whatsapp_number', models.CharField(default='919876543210', max_length=20)),
                ('jar_emoji', models.CharField(default='🫙', max_length=10)),
                ('stats_json', models.JSONField(default=list)),
                ('float_badges_json', models.JSONField(default=list)),
                ('is_visible', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Section',
            },
        ),
    ]
