# Generated by Django 5.2.4 on 2026-03-30 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herosection',
            name='btn_primary_text',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='btn_primary_url',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='btn_secondary_text',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='whatsapp_number',
        ),
        migrations.AddField(
            model_name='herosection',
            name='buttons_json',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='herosection',
            name='hero_image_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
