# Generated by Django 5.2.4 on 2026-03-30 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_herosection_btn_primary_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_json', models.JSONField(default=list, help_text='List of feature cards: [{"ico":"🚚","title":"Free Delivery","sub":"Orders above ₹499"}, ...]')),
                ('is_visible', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Features Section',
                'verbose_name_plural': 'Features Section',
            },
        ),
    ]
