# Generated by Django 6.0.3 on 2026-03-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfferBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_type', models.CharField(choices=[('main', 'Main Offer Banner'), ('potw', 'Pickle of the Week')], default='main', max_length=10)),
                ('name', models.CharField(help_text='Product name (e.g., Andhra Avakaya Mango Pickle)', max_length=200)),
                ('price', models.DecimalField(decimal_places=2, help_text='Sale price (₹)', max_digits=10)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, help_text='Original crossed-out price (₹)', max_digits=10, null=True)),
                ('url', models.CharField(blank=True, help_text='Relative URL or full link (e.g., /product/mango-pickle/)', max_length=255, null=True)),
                ('badge', models.CharField(blank=True, help_text='e.g., 🔥 LIMITED STOCK', max_length=50, null=True)),
                ('description', models.CharField(blank=True, help_text='Short description for the main offer', max_length=255, null=True)),
                ('discount_label', models.CharField(blank=True, help_text='e.g., 33% OFF', max_length=30, null=True)),
                ('emoji', models.CharField(blank=True, default='', help_text='Emoji for the POTW banner', max_length=10, null=True)),
                ('weight_type', models.CharField(blank=True, help_text='e.g., 500g | Traditional Recipe', max_length=100, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Controls the sequence they appear on the frontend')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this banner from the frontend')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Offer Banner',
                'verbose_name_plural': 'Offer Banners',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
