# Generated by Django 5.2.4 on 2026-03-31 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(blank=True, max_length=200, null=True)),
                ('admin_email', models.CharField(blank=True, max_length=200, null=True)),
                ('admin_password', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(default='🏷️', max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('url', models.CharField(blank=True, default='/', max_length=300, null=True)),
                ('product_count', models.PositiveIntegerField(default=0, help_text='Shown as count badge in filter sidebar')),
                ('order', models.PositiveIntegerField(default=0, help_text='Controls display order')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CategorySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(default='Shop by Category', max_length=200)),
                ('section_subtitle', models.CharField(default='Browse our wide range of authentic pickle varieties', max_length=300)),
                ('items_json', models.JSONField(default=list, help_text='List of category cards: [{"emoji":"🥭","name":"Mango Pickle","count":"32 products","url":"/category/mango/","bg_gradient":"linear-gradient(135deg,#fff3e0,#ffcc80)"}, ...]')),
                ('is_visible', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category Section',
                'verbose_name_plural': 'Category Section',
            },
        ),
        migrations.CreateModel(
            name='FeaturesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_json', models.JSONField(default=list, help_text='List of feature cards: [{"ico":"🚚","title":"Free Delivery","sub":"Orders above ₹499"}, ...]')),
                ('is_visible', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Features Section',
                'verbose_name_plural': 'Features Section',
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default="🏆 Nagpur's #1 Pickle Store", max_length=200)),
                ('title_line1', models.CharField(default='Discover', max_length=200)),
                ('title_highlight', models.CharField(default='Rare & Exclusive', max_length=200)),
                ('title_line2', models.CharField(default='Pickle Brands', max_length=200)),
                ('subtitle', models.TextField(default='Handpicked regional pickles from Andhra, Rajasthan, Punjab & more — not available in local stores. Order online with 24-hour delivery across Nagpur.')),
                ('jar_emoji', models.CharField(default='🫙', max_length=10)),
                ('hero_image_url', models.TextField(blank=True, default='')),
                ('buttons_json', models.JSONField(default=list)),
                ('stats_json', models.JSONField(default=list)),
                ('float_badges_json', models.JSONField(default=list)),
                ('is_visible', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Section',
            },
        ),
        migrations.CreateModel(
            name='NewsletterSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default=' Get 15% OFF Your First Order!', max_length=200)),
                ('description', models.TextField(default='Subscribe to receive exclusive deals, new pickle arrivals & Nagpur-only offers straight to your inbox.')),
                ('placeholder', models.CharField(default='Enter your email address...', max_length=100)),
                ('btn_text', models.CharField(default='Subscribe 🎉', max_length=50)),
                ('privacy_note', models.CharField(default='No spam. Unsubscribe anytime. 🔒 Privacy protected.', max_length=200)),
                ('url', models.CharField(blank=True, default='/newsletter/subscribe/', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='OfferBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_type', models.CharField(choices=[('main', 'Main Offer Banner'), ('potw', 'Pickle of the Week')], default='main', max_length=10)),
                ('name', models.CharField(help_text='Product name (e.g., Andhra Avakaya Mango Pickle)', max_length=200)),
                ('price', models.DecimalField(decimal_places=2, help_text='Sale price (₹)', max_digits=10)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, help_text='Original crossed-out price (₹)', max_digits=10, null=True)),
                ('url', models.CharField(blank=True, help_text='Relative URL or full link (e.g., /product/mango-pickle/)', max_length=255, null=True)),
                ('badge', models.CharField(blank=True, help_text='e.g., 🔥 LIMITED STOCK', max_length=50, null=True)),
                ('description', models.CharField(blank=True, help_text='Short description for the main offer', max_length=255, null=True)),
                ('discount_label', models.CharField(blank=True, help_text='e.g., 33% OFF', max_length=30, null=True)),
                ('emoji', models.CharField(blank=True, default='', help_text='Emoji for the POTW banner', max_length=10, null=True)),
                ('weight_type', models.CharField(blank=True, help_text='e.g., 500g | Traditional Recipe', max_length=100, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Controls the sequence they appear on the frontend')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this banner from the frontend')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Offer Banner',
                'verbose_name_plural': 'Offer Banners',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.CharField(default='', help_text='Emoji or short text', max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('rating', models.IntegerField(default=5, help_text='1 to 5 stars')),
                ('text', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
