# Generated by Django 6.0.3 on 2026-04-02 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admindetails',
            name='admin_phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
