# Generated by Django 6.0.3 on 2026-04-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0002_admindetails_admin_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=200, null=True)),
                ('user_email', models.CharField(blank=True, max_length=200, null=True)),
                ('user_phone', models.CharField(blank=True, max_length=200, null=True)),
                ('user_city', models.CharField(blank=True, max_length=200, null=True)),
                ('user_password', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
