# Generated by Django 6.0.3 on 2026-03-31 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0003_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default=' Get 15% OFF Your First Order!', max_length=200)),
                ('description', models.TextField(default='Subscribe to receive exclusive deals, new pickle arrivals & Nagpur-only offers straight to your inbox.')),
                ('placeholder', models.CharField(default='Enter your email address...', max_length=100)),
                ('btn_text', models.CharField(default='Subscribe 🎉', max_length=50)),
                ('privacy_note', models.CharField(default='No spam. Unsubscribe anytime. 🔒 Privacy protected.', max_length=200)),
                ('url', models.CharField(blank=True, default='/newsletter/subscribe/', max_length=500)),
            ],
        ),
    ]
