# Generated by Django 6.0.3 on 2026-04-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0003_userdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='user_register_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='user_register_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
