# Generated by Django 6.0.3 on 2026-03-31 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0004_newslettersetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(blank=True, max_length=200, null=True)),
                ('admin_email', models.CharField(blank=True, max_length=200, null=True)),
                ('admin_password', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
