# Generated by Django 5.2.4 on 2026-03-31 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_category_filter', models.BooleanField(default=True)),
                ('show_brand_filter', models.BooleanField(default=True)),
                ('show_price_filter', models.BooleanField(default=True)),
                ('show_region_filter', models.BooleanField(default=True)),
                ('show_rating_filter', models.BooleanField(default=True)),
                ('show_weight_filter', models.BooleanField(default=True)),
                ('price_min', models.PositiveIntegerField(default=50)),
                ('price_max', models.PositiveIntegerField(default=800)),
                ('regions_json', models.JSONField(default=list, help_text='[{"name":"Andhra Pradesh","count":35}, ...]')),
                ('weights_json', models.JSONField(default=list, help_text='[{"label":"100g - 200g"}, ...]')),
                ('page_title', models.CharField(default='All Pickles - Shop by Brand, Category & Region | PickleHub Nagpur', max_length=200)),
                ('whatsapp_number', models.CharField(default='919876543210', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product Page Settings',
                'verbose_name_plural': 'Product Page Settings',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(default='🫙', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('name', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('weight', models.CharField(default='500g', max_length=100)),
                ('oil_type', models.CharField(default='Mustard Oil', max_length=100)),
                ('region', models.CharField(blank=True, default='', help_text='e.g. Andhra Pradesh, Rajasthan', max_length=200)),
                ('badge', models.CharField(blank=True, choices=[('Bestseller', 'Bestseller'), ('New Arrival', 'New Arrival'), ('Premium', 'Premium'), ('Hot 🔥', 'Hot 🔥'), ('Organic', 'Organic'), ('Limited', 'Limited'), ('Rare Find', 'Rare Find'), ('Nagpur Special', 'Nagpur Special'), ('', 'No Badge')], default='', max_length=50)),
                ('badge_color', models.CharField(default='linear-gradient(135deg,#e85d04,#f48c06)', help_text='CSS gradient for the badge background', max_length=200)),
                ('card_bg', models.CharField(default='linear-gradient(135deg,#fff3e0,#ffcc80)', help_text='CSS gradient for product card background', max_length=200)),
                ('price', models.PositiveIntegerField(default=0, help_text='Sale price in ₹')),
                ('old_price', models.PositiveIntegerField(default=0, help_text='Original price in ₹')),
                ('discount', models.CharField(blank=True, default='', help_text='e.g. 29% off — auto-calculated or manual override', max_length=20)),
                ('stock', models.PositiveIntegerField(default=100)),
                ('low_stock_threshold', models.PositiveIntegerField(default=20)),
                ('low_stock_label', models.CharField(blank=True, default='', help_text='e.g. "🔥 Only 12 left" — leave blank to auto-generate', max_length=100)),
                ('rating', models.DecimalField(decimal_places=1, default=4.5, max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('whatsapp_number', models.CharField(default='919876543210', help_text='Without + sign e.g. 919876543210', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show in Best Sellers / homepage featured grid')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='Admin_app.brand')),
                ('category', models.ForeignKey(blank=True, help_text='Links to CategorySection for filter sidebar', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='Admin_app.categorysection')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
